import { existsSync, mkdirSync, readFileSync, rmSync } from 'fs';
import { describe, expect, test } from 'vitest';
import { version } from '../package.json';
import { CHUNK } from '../src/const';
import { writeSitemap } from '../src/helpers/global.helper';

describe('Creating files', () => {
  const json = [
    {
      page: 'https://example.com/flat/'
    },
    {
      page: 'https://example.com/'
    },
    {
      page: 'https://example.com/page1/'
    },
    {
      page: 'https://example.com/page1/flat1/'
    },
    {
      page: 'https://example.com/page2/'
    },
    {
      page: 'https://example.com/page1/subpage1/'
    },
    {
      page: 'https://example.com/page2/subpage2/'
    },
    {
      page: 'https://example.com/page2/subpage2/subsubpage2/'
    }
  ];

  const cleanMap = (folder: string) => {
    if (existsSync(folder)) {
      rmSync(folder, { recursive: true, force: true });
    }
  };

  test('Sitemap.xml was created and contains right data', async () => {
    const f = 'build-test-1';
    cleanMap(f);
    mkdirSync(f);
    writeSitemap(json, { outDir: f }, 'example.com');

    expect(existsSync(`${f}/sitemap.xml`)).toBe(true);
    const fileContent = readFileSync(`${f}/sitemap.xml`, { encoding: 'utf-8' });
    expect(fileContent).toContain('https://example.com/flat/');
    expect((fileContent.match(/<url>/g) || []).length).toEqual(8);

    cleanMap(f);
  });

  test('Sitemap.xml is exact', async () => {
    CHUNK.maxSize = 8;
    const f = 'build-test-2';

    cleanMap(f);
    mkdirSync(f);
    writeSitemap(json, { outDir: f }, 'https://example.com');

    expect(existsSync(`${f}/sitemap.xml`)).toBe(true);
    const fileContent = readFileSync(`${f}/sitemap.xml`, { encoding: 'utf-8' });

    expect(fileContent).toContain(`<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <!-- This file was automatically generated by https://github.com/bartholomej/svelte-sitemap v${version} -->
  <url>
    <loc>https://example.com/flat/</loc>
  </url>
  <url>
    <loc>https://example.com/</loc>
  </url>
  <url>
    <loc>https://example.com/page1/</loc>
  </url>
  <url>
    <loc>https://example.com/page1/flat1/</loc>
  </url>
  <url>
    <loc>https://example.com/page2/</loc>
  </url>
  <url>
    <loc>https://example.com/page1/subpage1/</loc>
  </url>
  <url>
    <loc>https://example.com/page2/subpage2/</loc>
  </url>
  <url>
    <loc>https://example.com/page2/subpage2/subsubpage2/</loc>
  </url>
</urlset>`);

    cleanMap(f);
  });

  test('Sitemap.xml and sub sitemaps for large pages was created and contains right data', async () => {
    CHUNK.maxSize = 5;
    const f = 'build-test-3';

    cleanMap(f);
    mkdirSync(f);
    writeSitemap(json, { outDir: f }, 'https://example.com');

    expect(existsSync(`${f}/sitemap.xml`)).toBe(true);

    const fileContent = readFileSync(`${f}/sitemap.xml`, { encoding: 'utf-8' });

    expect(fileContent).toContain('https://example.com/sitemap-1.xml');
    expect((fileContent.match(/<sitemap>/g) || []).length).toEqual(2);

    expect(existsSync(`${f}/sitemap-1.xml`)).toBe(true);
    expect(existsSync(`${f}/sitemap-2.xml`)).toBe(true);

    const fileContent2 = readFileSync(`${f}/sitemap-2.xml`, { encoding: 'utf-8' });
    expect(fileContent2).toContain('https://example.com/page2/subpage2/subsubpage2/');
    expect((fileContent2.match(/<url>/g) || []).length).toEqual(3);

    cleanMap(f);
  });

  test('Sitemap.xml respects changeFreq and lastMod', async () => {
    const f = 'build-test-4';
    const jsonWithData = [
      {
        page: 'https://example.com/',
        changeFreq: 'daily' as const,
        lastMod: '2026-03-04'
      }
    ];

    cleanMap(f);
    mkdirSync(f);
    writeSitemap(jsonWithData, { outDir: f }, 'https://example.com');

    const fileContent = readFileSync(`${f}/sitemap.xml`, { encoding: 'utf-8' });
    expect(fileContent).toContain('<changefreq>daily</changefreq>');
    expect(fileContent).toContain('<lastmod>2026-03-04</lastmod>');

    cleanMap(f);
  });

  test('Sitemap.xml without attribution', async () => {
    const f = 'build-test-5';
    cleanMap(f);
    mkdirSync(f);
    writeSitemap(json, { outDir: f, attribution: false }, 'https://example.com');

    const fileContent = readFileSync(`${f}/sitemap.xml`, { encoding: 'utf-8' });
    expect(fileContent).not.toContain('This file was automatically generated');

    cleanMap(f);
  });
});
