import { CHANGE_FREQ, IntegrationMethod } from '../const.js';

export type { IntegrationMethod };

export interface Arguments {
  /**
   * Your website domain URL (e.g., 'https://example.com').
   */
  domain: string;
  /**
   * Additional sitemap generation options.
   */
  options?: Options;
}

export interface Options {
  /**
   * Enable debug mode to display detailed log outputs during execution.
   * @default false
   */
  debug?: boolean;
  /**
   * How frequently the page content is likely to change.
   * This value provides general information to search engines and may not correlate exactly to how often they crawl the page.
   * @see {@link ChangeFreq}
   */
  changeFreq?: ChangeFreq;
  /**
   * If set to true, resets the last modified time (`lastmod`) of all pages to the current date/time.
   * @default false
   */
  resetTime?: boolean;
  /**
   * Custom build/output folder containing the static HTML files.
   * @default 'build'
   */
  outDir?: string;
  /**
   * Whether to include an attribution comment ("Generated by svelte-sitemap") in the output sitemap.xml.
   * @default true
   */
  attribution?: boolean;
  /**
   * Glob patterns or specific file/directory paths to exclude from the sitemap.
   * @default []
   * @example `ignore: ['**\/admin/**', 'my-secret-page']`
   */
  ignore?: string | string[];
  /**
   * Whether to append a trailing slash to all page URLs in the sitemap.
   * @default false
   */
  trailingSlashes?: boolean;
  /**
   * Array of additional page paths to manually add to the sitemap (e.g. paths external to SvelteKit or static assets).
   * @example `additional: ['my-page', 'my-second-page']`
   */
  additional?: string[];
  /**
   * Custom transform function that is called for each page entry.
   * It allows you to dynamically modify or filter page attributes (such as priority, changefreq, lastmod, alternateRefs).
   * Returning `null` or `undefined` excludes the page from the generated sitemap.
   *
   * @param config The resolved configuration object.
   * @param path The relative path of the page being processed.
   * @returns The modified sitemap field, or null/undefined to skip.
   */
  transform?: (
    config: OptionsSvelteSitemap,
    path: string
  ) => Promise<SitemapField | null | undefined> | SitemapField | null | undefined;
}

export interface OptionsSvelteSitemap extends Options {
  /**
   * Your website domain URL (e.g., 'https://example.com').
   */
  domain: string;
}

export interface SitemapFieldAlternateRef {
  /**
   * The alternative URL for the page (e.g. for different language versions).
   */
  href: string;
  /**
   * The language code (e.g. 'en', 'es') or 'x-default' for the alternate URL.
   */
  hreflang: string;
}

export interface SitemapField {
  /**
   * The location/URL of the page.
   */
  loc: string;
  /**
   * The last modified date/time of the page in ISO format.
   */
  lastmod?: string;
  /**
   * How frequently the page content is likely to change.
   * @see {@link ChangeFreq}
   */
  changefreq?: ChangeFreq;
  /**
   * The priority of this URL relative to other URLs on your site. Valid values range from 0.0 to 1.0.
   */
  priority?: number | string;
  /**
   * Alternative translations or language versions of the page.
   */
  alternateRefs?: Array<SitemapFieldAlternateRef>;
}

export interface PagesJson {
  /**
   * The path or URL of the page.
   */
  page?: string;
  /**
   * How frequently the page content is likely to change.
   */
  changeFreq?: ChangeFreq;
  /**
   * The last modified timestamp of the page.
   */
  lastMod?: string;
}

/**
 * Specs: https://www.sitemaps.org/protocol.html
 */
export type ChangeFreq = (typeof CHANGE_FREQ)[number];
