import { CHANGE_FREQ, IntegrationMethod } from '../const.js';

export type { IntegrationMethod };

export interface Arguments {
  /**
   * Your website domain URL (e.g., 'https://example.com').
   */
  domain: string;
  /**
   * Additional sitemap generation options.
   */
  options?: Options;
}

export interface Options {
  /**
   * Enable debug mode to display detailed log outputs during execution.
   * @default false
   */
  debug?: boolean;
  /**
   * How frequently the page content is likely to change.
   * This value provides general information to search engines and may not correlate exactly to how often they crawl the page.
   * @see {@link ChangeFreq}
   */
  changeFreq?: ChangeFreq;
  /**
   * If set to true, resets the last modified time (`lastmod`) of all pages to the current date/time.
   * @default false
   */
  resetTime?: boolean;
  /**
   * Custom build/output folder containing the static HTML files.
   * @default 'build'
   */
  outDir?: string;
  /**
   * Whether to include an attribution comment ("Generated by svelte-sitemap") in the output sitemap.xml.
   * @default true
   */
  attribution?: boolean;
  /**
   * Glob patterns or specific file/directory paths to exclude from the sitemap.
   * @default []
   * @example `ignore: ['**\/admin/**', 'my-secret-page']`
   */
  ignore?: string | string[];
  /**
   * Whether to append a trailing slash to all page URLs in the sitemap.
   * @default false
   */
  trailingSlashes?: boolean;
  /**
   * Array of additional page paths to manually add to the sitemap (e.g. paths external to SvelteKit or static assets).
   * @example `additional: ['my-page', 'my-second-page']`
   */
  additional?: string[];
  transform?: (
    config: OptionsSvelteSitemap,
    path: string
  ) => Promise<SitemapField | null> | SitemapField | null;
}

export interface OptionsSvelteSitemap extends Options {
  /**
   * Your website domain URL (e.g., 'https://example.com').
   */
  domain: string;
}

export interface SitemapFieldAlternateRef {
  href: string;
  hreflang: string;
}

export interface SitemapField {
  loc: string;
  lastmod?: string;
  changefreq?: ChangeFreq;
  priority?: number | string;
  alternateRefs?: Array<SitemapFieldAlternateRef>;
}

export interface PagesJson {
  /**
   * The path or URL of the page.
   */
  page?: string;
  /**
   * How frequently the page content is likely to change.
   */
  changeFreq?: ChangeFreq;
  /**
   * The last modified timestamp of the page.
   */
  lastMod?: string;
}

/**
 * Specs: https://www.sitemaps.org/protocol.html
 */
export type ChangeFreq = (typeof CHANGE_FREQ)[number];
