name: 🧪 Build and Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    name: 🧪 Build and Test

    steps:
      - uses: actions/checkout@v6

      - name: 📦 Enable Corepack
        run: corepack enable

      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'yarn'

      - name: 📦 Install dependencies
        run: yarn install --immutable

      - name: 🏗️ Build app
        run: yarn build

      - name: 🧪 Tests
        run: yarn test:coverage

      - name: Run tests with outDir
        run: yarn test:outdir

      # - name: Upload code coverage
      #   run: bash <(curl -s https://codecov.io/bash)
